eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
server:
    port: 8082
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/db_job
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
        ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        database: mysql


job-service:
    url: http://localhost:8082
company-service:
    url: http://localhost:8081
review-service:
    url: http://localhost:8083