eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://service-registry:8761/eureka/
management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
server:
    port: 8082
spring:
    application:
        name: job
    datasource:
        password: password
        url: jdbc:postgresql://postgres:5432/job_db
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                show_sql: true

job-service:
    url: http://job:8082
company-service:
    url: http://company:8081
review-service:
    url: http://review:8083