eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0
server:
    port: 8082
spring:
    application:
        name: job
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/job_db
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                show_sql: true